import json
import os
import asyncio
from pathlib import Path
from typing import Any, Dict, Literal
import httpx

import chainlit as cl

from backend.utils import relative_project_path


TRANSLATION_BASE_PATH = relative_project_path("public/locales")


def load_translations(lang: str) -> Dict[str, Any]:
    """Loads translation dictionary for a given language."""
    translation_base_path = relative_project_path("public/locales")
    translation_file_path = translation_base_path / lang / "translations.json"

    try:
        with open(translation_file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print(
            f"Warning: Translation file not found for language '{lang}' at '{translation_file_path}'. Falling back to 'en'."
        )
        # Fallback to English if the requested language file isn't found
        english_translation_path = translation_base_path / "en" / "translations.json"

        try:
            with open(english_translation_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except FileNotFoundError:
            print(
                f"Error: English translation file also not found at '{english_translation_path}'. Please check your public/locales structure."
            )
            return {}  # Return empty dict if fallback also fails
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from translation file '{translation_file_path}'.")
        return {}
    except Exception as e:
        print(f"An unexpected error occurred while loading translations: {e}")
        return {}


# def get_project_root_directory() -> Path:
#     """Returns the root directory of the application."""
#     return Path(__file__).parent.parent.parent


# def relative_project_path(path: os.PathLike) -> Path:
#     """
#     Returns a Path object that is relative to the app directory. If the provided path is absolute, it returns the path as is.

#     :param path: The path to convert.
#     :return: A Path object that is relative to the app directory.
#     """
#     path = Path(path)
#     if path.is_absolute():
#         return path
#     return get_project_root_directory() / path


async def is_ready(
    model: Literal["All", "Embedding", "Reranker"] = "All",
    timeout: int = 120,
    display_threshold: float = 2.0,
) -> bool:
    """
    Checks if the model is ready by sending a health check request.
    Returns True if the health check finishes within `display_threshold` seconds,
    otherwise returns False (indicating that the model is still loading).

    :param model: The model to check ("All", "Embedding", "Reranker").
    :param timeout: Maximum time to wait for the request.
    :param display_threshold: Time in seconds before we consider showing a "loading" message.
    :return: True if the model was ready within the display_threshold, else False.
    """

    async def check_health(url: str):
        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.get(url + "health")
            resp.raise_for_status()

    tasks = []

    if model in ["All", "Embedding"]:
        assert "TEI_EMBEDDING_ENDPOINT" in os.environ, "TEI_EMBEDDING_ENDPOINT environment variable is not set!"
        tasks.append(check_health(os.getenv("TEI_EMBEDDING_ENDPOINT")))

    if model in ["All", "Reranker"]:
        assert "TEI_RERANKER_ENDPOINT" in os.environ, "TEI_RERANKER_ENDPOINT environment variable is not set!"
        tasks.append(check_health(os.getenv("TEI_RERANKER_ENDPOINT")))

    # Wait for either all tasks to complete or display threshold reached
    try:
        await asyncio.wait_for(asyncio.gather(*tasks), timeout=display_threshold)
        return True  # Completed within display threshold
    except asyncio.TimeoutError:
        return False  # Took longer, we can show a "loading" message


async def run_warmup():
    ready = await is_ready()

    if not ready:
        await cl.context.emitter.send_toast("Embedding-Modelle werden geladen. Dies kann einige Sekunden dauern...")

        while not ready:
            ready = await is_ready()

        await cl.context.emitter.send_toast("Embedding-Modelle sind jetzt bereit!", type="success")


async def render_sources(message: cl.Message, display: Literal["side", "inline", "page"]) -> cl.Message:
    """
    Replaces the squared brackets generated by the LLM with the actual PDF sources.
    Now supports collection-relative paths from the enhanced metadata.
    """
    if "sources" in message.metadata:
        base_dir = os.getenv("DOCUMENT_BASE_PATH")
        assert base_dir, "DOCUMENT_BASE_PATH environment variable is not set!"
        base_dir = relative_project_path(base_dir)

        elements = []
        sources = message.metadata["sources"]
        for idx, source in enumerate(sources):
            # Use collection-relative path if available, otherwise fall back to filename
            if "filename" in source and "collection_name" in source:
                # New format: collection_name/[subdirectory/]filename
                collection_name = source["collection_name"]
                filename = source["filename"]
                subdirectory = source.get("subdirectory", "")

                # Build the full path: collection/subdirectory/filename
                if subdirectory:
                    file_path = base_dir / collection_name / subdirectory / filename
                    display_name = f"{collection_name}/{subdirectory}/{filename}"
                else:
                    file_path = base_dir / collection_name / filename
                    display_name = f"{collection_name}/{filename}"
            else:
                # Fallback to old format
                path = Path(source["file"])
                file_path = base_dir / path if not path.is_absolute() else path
                display_name = path.name
                filename = path.name

            pages = source.get("pages", [1])

            # If the source was cited, replace the placeholder with the actual element
            if f"[{idx+1}]" in message.content:
                element_name = f"{filename}, Seite{'n' if len(pages) > 1 else ''} {pages[0] if len(pages) == 1 else str(pages[0]) + '-' + str(pages[-1])}"
                message.content = message.content.replace(f"[{idx+1}]", element_name)

                # Only add to elements if the file actually exists
                if file_path.exists():
                    elements.append(
                        cl.Pdf(
                            name=element_name,
                            path=str(file_path),
                            display=display,
                            page=pages[0],
                        )
                    )
                else:
                    print(f"Warning: Source file not found: {file_path}")

        message.elements.extend(elements)

    return message
